### ISSUE TITLE
Working Area Render Causes OpenGL wierdness

### ISSUE THREAD

**Issue by Buuz135** [faceofcat/Tesla-Core-Lib#12]
Thicker and extra lines in the Blocks Bounding Boxes and disables other OpenGL renders behind it, like the rest of the bounding box.
![](https://i.imgur.com/90Rzl7G.png)

**Comment by Buuz135** [comment]
Feedback on the commit, bounding boxes extra lines and thickness is fixed but the missing extra renders are still missing. But just some of them, as you can see, water render disapears but the chest ant the lava works.
![](https://i.imgur.com/rXAxPce.png)
![](https://i.imgur.com/l49Jvh7.png)

**Comment by faceofcat** [comment]
yeah... I blame that on water!... :)

**Comment by Buuz135** [comment]
Blame it on transparent fluids because all the transparent ones doesn't render

**Comment by faceofcat** [comment]
this should work better now... at least water should render fine behind it.
