### ISSUE TITLE
Survival Multiplayer - Stone gears not craftable

### ISSUE THREAD

**Issue by Satrman** [faceofcat/Tesla-Core-Lib#18]
As says the title, Stone gears are non-craftable with any of the recipies.

Current installed mods are as follows:
Coder Pack, Forge Mod Loader, Forge, Just Enough Items, AppleSkin, Baubles, BD Lib, BiblioCraft, Biomes O' Plenty, Botania, Chameleon, Chest Transporter, Cooking for Blockheads, Fast Leaf Decay, Mantle, Natura, Shadowfacts' Forgelin, GenDustry, Forestry, Waila, Mekanism, Tesla Core Lib, Industrial Foregoing, Inventory Tweaks, journeyMap, MekanismGenerators, MekanismTools, MorePlayerModels, Mouse Tweaks, Pam's HarvestCraft, StorageDrawers, bspkrsCore, Treecapitator, Waila Harvestability, Tesla Core Lib Registries

If any assistance is avalible it would be appreciated, it stinks waiting for somebody with creative permissions to get on, give them the materials, and get gears from creative spawning.
![image](https://user-images.githubusercontent.com/32682998/31401572-511368da-adc1-11e7-9233-71b9ae90e0fa.png)

**Comment by faceofcat** [comment]
what version of the mod?... and of the lib?... 

also... does JEI show any recipes for the gear?

**Comment by Satrman** [comment]
Lib versions are 1.12-1.0.8 for Tesla Core Lib, BD Lib is 1.14.2.8, and Tesla Core Lib Registries is 1.12-1.0.8

JEI does show the recipie, that's in the provided screenshot, and the version for the other mods are as follows

Coder Pack(9.19), Forge Mod Loader(8.0.99.99), Forge(14.22.0.2475), Just Enough Items(4.7.8.94), AppleSkin(1.0.8), Baubles(1.12-1.5.1), BD Lib(1.14.2.8), BiblioCraft(2.4.3), Biomes O' Plenty(7.0.0), Botania(r1.10-347), Chameleon(1.12-4.1.3), Chest Transporter(1.12-2.8.7), Cooking for Blockheads(6.3.6), Fast Leaf Decay(v14), Mantle(1.3.1.21), Natura(1.12-4.3.0.16), Shadowfacts' Forgelin(1.5.1), GenDustry(1.6.5.4), Forestry(5.5.5.191), Waila(1.8.20), Mekanism(9.4.1), Tesla Core Lib(1.12-1.0.8), Industrial Foregoing(1.12-1.2.1-48), Inventory Tweaks(1.63+beta.108.6ff67c4), journeyMap(1.12.1-5.5.0b4), MekanismGenerators(9.4.1), MekanismTools(9.4.1), MorePlayerModels(1.12), Mouse Tweaks(2.8), Pam's HarvestCraft(1.12a), StorageDrawers(1.12.1-5.3.2), bspkrsCore(at_0.9), Treecapitator(No Update Version Listed), Waila Harvestability(1.1.11), Tesla Core Lib Registries(1.12-1.0.8)

**Comment by Satrman** [comment]
![image](https://user-images.githubusercontent.com/32682998/31404117-2683bcc0-adc9-11e7-8cc9-1b8828ae5028.png)
Here is a list of "gear" items as searched via JEI

**Comment by faceofcat** [comment]
can you try upgrading to 1.0.9 ?

**Comment by Satrman** [comment]
I'll ask the owner to try that

**Comment by faceofcat** [comment]
this should be fixed in later versions.
