### ISSUE TITLE
[1.10.2] [SMP] Crash on server startup 

### ISSUE THREAD

**Issue by b0bst3r** [faceofcat/Tesla-Core-Lib#2]
http://pastebin.ubuntu.com/24114256/

mekfarm-1.10.2-0.3.0
tesla-core-lib-1.10.2-0.3.0.jar
Forge 12.18.3.2221

**Comment by faceofcat** [comment]
what was it?... :)

**Comment by b0bst3r** [comment]
I opened it on the wrong github so I closed this and reopened on mekfarm :)
