### ISSUE TITLE
Incompatibility with Sponge

### ISSUE THREAD

**Issue by LXGaming** [faceofcat/Tesla-Core-Lib#21]
According to the error your mod is calling `notifyNeighborsOfStateChange` async when it should be called on the Main Thread.

Running the following:
- spongeforge-1.12.2-2503-7.0.0-BETA-2706
- tesla-core-lib-1.12-1.0.9.jar

Error: https://pastebin.com/WyDeV57g

**Comment by faceofcat** [comment]
well... I have no knowledge of Sponge and no time to dig into it right now... if you have a solution for this please let me know... :)
