### ISSUE TITLE
Generators transfering power clientside crashing PowerCells 

### ISSUE THREAD

**Issue by Buuz135** [faceofcat/Tesla-Core-Lib#25]
Power should only be sent server side.
https://github.com/Buuz135/Industrial-Foregoing/issues/98
https://github.com/TechReborn/TechReborn/issues/1161

**Comment by power-spike** [comment]
I am getting this issue as well. 

Running a server, and anytime a client goes anywhere near the area, we are getting client side crashes. 

What caused the issue: the player in question placed down a Petrified Fuel Generator from Industrial Forgoing and crashed to desktop. 

Anyone who now goes near the area crashes to desktop. 

https://pastebin.com/06J7hTx5

(Excert from log)

**Comment by faceofcat** [comment]
this was probably fixed a while ago... I see the generator code tests for `!world.isRemote` before distributing power.
