### ISSUE TITLE
Unnecessary network spam

### ISSUE THREAD

**Issue by sironin** [faceofcat/Tesla-Core-Lib#3]
All machines that are loaded are sending full updates to every player on the server (even cross dimensional), issue forwarded at request of industrial foregoing: https://github.com/Buuz135/Industrial-Foregoing/issues/9

**Comment by faceofcat** [comment]
I think I know how to fix this... give me a couple of days to find some time for this and I'll do it.

Currently spending my free time reorganizing and converting this lib to kotlin for 1.12...

**Comment by faceofcat** [comment]
should be fixed in 0.7.1 version of the mod.
