### ISSUE TITLE
Game crashes as soon as i put in Tesla Corelib in to my Mods Folder

### ISSUE THREAD

**Issue by juuliiiiaaaan** [faceofcat/Tesla-Core-Lib#33]
Hello,

so i wanna use Tesla Corelib for 1.11.2. But i got a problem. As soon as it put in the mod in to the mods folder my game doesnt start. It says : "The game crashed whilst there was a severe problem during mod loading that has caused the game to fail". And when i click on "More Details" it says : "The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tesla Core Lib (teslacorelib)"  Can pls someone help me! Thank you!

**Comment by faceofcat** [comment]
do you also have `Tesla` in there?... I believe that's required for 1.11.

**Comment by faceofcat** [comment]
also... please provide a full game log.
