### ISSUE TITLE
1.12.2 Crashes on launch. something about "Invalid shapeless ore recipe"

### ISSUE THREAD

**Issue by truehunterethan** [faceofcat/Tesla-Core-Lib#34]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Invalid shapeless ore recipe: null, 1xitem.bam_tshirt@0

when i hit "View crash report' nothing happens

EDIT: Found the crash file
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-0.12-78-core.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 3/17/18 12:28 AM
Description: Initializing game

java.lang.RuntimeException: Invalid shapeless ore recipe: null, 1xitem.bam_tshirt@0
	at net.minecraftforge.oredict.ShapelessOreRecipe.<init>(ShapelessOreRecipe.java:84)
	at com.kashdeya.tinyprogressions.registry.recipes.ShapelessRecipe.<init>(ShapelessRecipe.java:24)
	at com.kashdeya.tinyprogressions.recipes.ArmorRecipes.init(ArmorRecipes.java:57)
	at com.kashdeya.tinyprogressions.main.TinyProgressions.registerRecipes(TinyProgressions.java:126)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_522_TinyProgressions_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:746)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:622)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:718)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.oredict.ShapelessOreRecipe.<init>(ShapelessOreRecipe.java:84)
	at com.kashdeya.tinyprogressions.registry.recipes.ShapelessRecipe.<init>(ShapelessRecipe.java:24)
	at com.kashdeya.tinyprogressions.recipes.ArmorRecipes.init(ArmorRecipes.java:57)
	at com.kashdeya.tinyprogressions.main.TinyProgressions.registerRecipes(TinyProgressions.java:126)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_522_TinyProgressions_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:746)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:622)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:718)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 921294480 bytes (878 MB) / 3762814976 bytes (3588 MB) up to 7874281472 bytes (7509 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8448m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2627 72 mods loaded, 72 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version                  | Source                                            | Signature                                |
	|:----- |:------------------------ |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft                | 1.12.2                   | minecraft.jar                                     | None                                     |
	| UCH   | mcp                      | 9.42                     | minecraft.jar                                     | None                                     |
	| UCH   | FML                      | 8.0.99.99                | forge-1.12.2-14.23.2.2627.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                    | 14.23.2.2627             | forge-1.12.2-14.23.2.2627.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | actuallyadditions        | 1.12.2-r132              | ActuallyAdditions-1.12.2-r132.jar                 | None                                     |
	| UCH   | baubles                  | 1.5.2                    | Baubles-1.12-1.5.2.jar                            | None                                     |
	| UCH   | actuallybaubles          | 1.1                      | ActuallyBaubles-1.12-1.1.jar                      | None                                     |
	| UCH   | ctm                      | MC1.12-0.2.3.12          | CTM-MC1.12-0.2.3.12.jar                           | None                                     |
	| UCH   | chisel                   | MC1.12.2-0.2.0.31        | Chisel-MC1.12.2-0.2.0.31.jar                      | None                                     |
	| UCH   | crafttweaker             | 4.1.6                    | CraftTweaker2-1.12-4.1.6.jar                      | None                                     |
	| UCH   | mtlib                    | 3.0.4                    | MTLib-3.0.4.jar                                   | None                                     |
	| UCH   | modtweaker               | 4.0.8                    | modtweaker-4.0.8.jar                              | None                                     |
	| UCH   | jei                      | 4.8.5.147                | jei_1.12.2-4.8.5.147.jar                          | None                                     |
	| UCH   | mantle                   | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                          | None                                     |
	| UCH   | tconstruct               | 1.12.2-2.9.1.65          | TConstruct-1.12.2-2.9.1.65.jar                    | None                                     |
	| UCH   | extrautils2              | 1.0                      | extrautils2-1.12-1.7.4.jar                        | None                                     |
	| UCH   | flyringbaublemod         | 0.3.1_1.12-d4e654e       | angelRingToBauble-1.12-0.3.1.50+d4e654e.jar       | None                                     |
	| UCH   | appleskin                | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                        | None                                     |
	| UCH   | aroma1997core            | 1.3.0.2                  | Aroma1997Core-1.12.2-1.3.0.2.jar                  | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCH   | aroma1997sdimension      | 1.3.0.0.b37              | Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar | None                                     |
	| UCH   | bdlib                    | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                      | None                                     |
	| UCH   | betterbuilderswands      | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar   | None                                     |
	| UCH   | bookshelf                | 2.3.535                  | Bookshelf-1.12.2-2.3.535.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | buildcraftlib            | 7.99.15                  | buildcraft-7.99.15.jar                            | None                                     |
	| UCH   | buildcraftcore           | 7.99.15                  | buildcraft-7.99.15.jar                            | None                                     |
	| UCH   | buildcraftbuilders       | 7.99.15                  | buildcraft-7.99.15.jar                            | None                                     |
	| UCH   | buildcraftenergy         | 7.99.15                  | buildcraft-7.99.15.jar                            | None                                     |
	| UCH   | buildcraftfactory        | 7.99.15                  | buildcraft-7.99.15.jar                            | None                                     |
	| UCH   | buildcraftrobotics       | 7.99.15                  | buildcraft-7.99.15.jar                            | None                                     |
	| UCH   | buildcraftsilicon        | 7.99.15                  | buildcraft-7.99.15.jar                            | None                                     |
	| UCH   | buildcrafttransport      | 7.99.15                  | buildcraft-7.99.15.jar                            | None                                     |
	| UCH   | chameleon                | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                          | None                                     |
	| UCH   | chesttransporter         | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar                 | None                                     |
	| UCH   | codechickenlib           | 3.1.6.339                | CodeChickenLib-1.12.2-3.1.6.339-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | cyclopscore              | 0.11.5                   | CyclopsCore-1.12.2-0.11.5.jar                     | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCH   | commoncapabilities       | 1.4.0                    | CommonCapabilities-1.12-1.4.0.jar                 | None                                     |
	| UCH   | storagedrawers           | 1.12-5.2.5               | StorageDrawers-1.12.2-5.3.5.jar                   | None                                     |
	| UCH   | refinedstorage           | 1.5.32                   | refinedstorage-1.5.32.jar                         | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| UCH   | compactmachines3         | 3.0.7                    | compactmachines3-1.12.2-3.0.7-b197.jar            | None                                     |
	| UCH   | ctgui                    | 1.0.0                    | CraftTweaker2-1.12-4.1.6.jar                      | None                                     |
	| UCH   | crafttweakerjei          | 2.0.0                    | CraftTweaker2-1.12-4.1.6.jar                      | None                                     |
	| UCH   | darkutils                | 1.8.200                  | DarkUtils-1.12.2-1.8.200.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | elevatorid               | 1.3.6                    | ElevatorMod-1.12.2-1.3.6.jar                      | None                                     |
	| UCH   | enderstorage             | 2.4.2.126                | EnderStorage-1.12.2-2.4.2.126-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | tesla                    | 1.0.63                   | Tesla-1.12.2-1.0.63.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | theoneprobe              | 1.4.20                   | theoneprobe-1.12-1.4.20.jar                       | None                                     |
	| UCH   | immersiveengineering     | 0.12-78                  | ImmersiveEngineering-0.12-78.jar                  | None                                     |
	| UCH   | redstoneflux             | 2.0.1                    | RedstoneFlux-1.12-2.0.1.2-universal.jar           | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCH   | exchangers               | 1.12.2-2.7.1             | Exchangers-1.12.2-2.7.1.jar                       | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| UCH   | fastleafdecay            | v14                      | FastLeafDecay-v14.jar                             | None                                     |
	| UCH   | forgelin                 | 1.6.0                    | Forgelin-1.6.0.jar                                | None                                     |
	| UCH   | ftblib                   | 5.0.0.14                 | FTBLib-5.0.0.14.jar                               | None                                     |
	| UCH   | ftbutilities             | 5.0.0.11                 | FTBUtilities-5.0.0.11.jar                         | None                                     |
	| UCH   | advgenerators            | 0.9.20.12                | generators-0.9.20.12-mc1.12.2.jar                 | None                                     |
	| UCH   | gravestone               | 1.10.1                   | gravestone-1.10.1.jar                             | None                                     |
	| UCH   | teslacorelib             | 1.0.13                   | tesla-core-lib-1.12-1.0.13.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCH   | industrialforegoing      | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.8.5-127.jar          | None                                     |
	| UCH   | integrateddynamics       | 0.11.7                   | IntegratedDynamics-1.12.2-0.11.7.jar              | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCH   | integrateddynamicscompat | 1.0.0                    | IntegratedDynamics-1.12.2-0.11.7.jar              | None                                     |
	| UCH   | inventorytweaks          | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                          | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | ironbackpacks            | 1.12.2-3.0.5-6           | IronBackpacks-1.12.2-3.0.5-6.jar                  | None                                     |
	| UCH   | journeymap               | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                       | None                                     |
	| UCH   | jeresources              | 0.8.5.27                 | JustEnoughResources-1.12.2-0.8.5.27.jar           | None                                     |
	| UCH   | lootbags                 | 2.5.4b                   | LootBags-1.12.2-2.5.4b.jar                        | None                                     |
	| UCH   | modnametooltip           | 1.10.0                   | modnametooltip_1.12.2-1.10.0.jar                  | None                                     |
	| UCH   | mousetweaks              | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                      | None                                     |
	| UCH   | rangedpumps              | 0.5                      | rangedpumps-0.5.jar                               | None                                     |
	| UCH   | refinedstorageaddons     | 0.2                      | refinedstorageaddons-0.2.jar                      | None                                     |
	| UCH   | snad                     | 1.12.1-1.7.09.16a        | Snad-1.12.1-1.7.09.16a.jar                        | None                                     |
	| UCH   | tinkertoolleveling       | 1.12-1.0.3.DEV.56fac4f   | TinkerToolLeveling-1.12-1.0.3.jar                 | None                                     |
	| UCH   | tp                       | 3.2.20                   | tinyprogressions-1.12.2-3.3.22-Release.jar        | None                                     |
	| UCH   | teslacorelib_registries  | 1.0.13                   | tesla-core-lib-1.12-1.0.13.jar                    | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-0.12-78-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
ForgelinPlugin (Forgelin-1.6.0.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 390.65' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* actuallyadditionsapi (33) from ActuallyAdditions-1.12.2-r132.jar
		* Baubles|API (1.4.0.2) from Baubles-1.12-1.5.2.jar
		* BetterWithModsAPI (Beta 0.6) from AppleSkin-mc1.12-1.0.9.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.99.15.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.99.15.jar
		* BuildCraftAPI|core (2.2) from buildcraft-7.99.15.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.99.15.jar
		* BuildCraftAPI|enums (1.0) from buildcraft-7.99.15.jar
		* BuildCraftAPI|events (2.0) from buildcraft-7.99.15.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.99.15.jar
		* BuildCraftAPI|filler (5.0) from buildcraft-7.99.15.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.99.15.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.99.15.jar
		* BuildCraftAPI|items (1.1) from buildcraft-7.99.15.jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.99.15.jar
		* BuildCraftAPI|lists (1.0) from buildcraft-7.99.15.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.99.15.jar
		* BuildCraftAPI|recipes (3.0) from buildcraft-7.99.15.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.99.15.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.99.15.jar
		* BuildCraftAPI|tiles (1.2) from buildcraft-7.99.15.jar
		* BuildCraftAPI|tools (1.0) from buildcraft-7.99.15.jar
		* BuildCraftAPI|transport (5.0) from buildcraft-7.99.15.jar
		* chesttransporter|api (2) from ChestTransporter-1.12.2-2.8.8.jar
		* Chisel-API (0.0.1) from Chisel-MC1.12.2-0.2.0.31.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.12.2-0.2.0.31.jar
		* commoncapabilities|api (0.0.1) from CommonCapabilities-1.12-1.4.0.jar
		* ctm-api (0.1.0) from CTM-MC1.12-0.2.3.12.jar
		* ctm-api-events (0.1.0) from CTM-MC1.12-0.2.3.12.jar
		* ctm-api-models (0.1.0) from CTM-MC1.12-0.2.3.12.jar
		* ctm-api-textures (0.1.0) from CTM-MC1.12-0.2.3.12.jar
		* ctm-api-utils (0.1.0) from CTM-MC1.12-0.2.3.12.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.12-78.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.12-78.jar
		* industrialforegoingapi (3) from industrialforegoing-1.12.2-1.8.5-127.jar
		* integrateddynamics|api (0.2.0) from IntegratedDynamics-1.12.2-0.11.7.jar
		* jeresources|API (0.8.5.27) from JustEnoughResources-1.12.2-0.8.5.27.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.2.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.8.5.147.jar
		* MouseTweaks|API (1.0) from MouseTweaks-2.8-mc1.12.1.jar
		* StorageDrawersAPI (2.1.0) from StorageDrawers-1.12.2-5.3.5.jar
		* StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12.2-5.3.5.jar
		* StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12.2-5.3.5.jar
		* StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12.2-5.3.5.jar
		* StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12.2-5.3.5.jar
		* StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12.2-5.3.5.jar
		* theoneprobe_api (1.4.4) from theoneprobe-1.12-1.4.20.jar
	Launched Version: forge-14.23.2.2627
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 390.65, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz

**Comment by faceofcat** [comment]
what makes you think it is related to Tesla Core Lib? :)

**Comment by truehunterethan** [comment]
because whenever i look up "Error: java.lang.RuntimeException: Invalid shapeless ore recipe: null, 1xitem.bam_tshirt@0" only stuff from Tesla Core Lib..

**Comment by truehunterethan** [comment]
and it only crashed after i added tesla core lib

**Comment by truehunterethan** [comment]
NVM. i have to find this prbb on my own cause it doesnt seem to be TCL

**Comment by NAGE1203** [comment]
In Stoneblock 2 I was trying to make an automated brewing system for growing crystals and after shift-clicking, a water bottle into the potion brewer the game crashed and I can't load the world any longer. PLEASE fix this issue ASAP
