### ISSUE TITLE
1.11.2: Game crash when I add Tesla-Core-Lib "java.lang.NoClassDefFoundError"

### ISSUE THREAD

**Issue by ghost** [faceofcat/Tesla-Core-Lib#36]
Stacktrace: https://pastebin.com/6Mf8Na0E

I have the recommended forge version for 1.11.2
I've tested with and without mods, despite what the log says, and have gone the extra step and have created a fresh .minecraft folder.

Using Tesla-Core-Lib Version 0.7.3 1.11.2

**Comment by faceofcat** [comment]
are you missing the 'tesla' library?

**Comment by faceofcat** [comment]
you probably were.
