### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by LuxerTheGamer** [faceofcat/Tesla-Core-Lib#4]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (Inventory Tweaks [1.62].jar)
  AstralCore (Astral Sorcery [1.4.4].jar)
  CTMCorePlugin (Connected Textures [0.1.1.6].jar)
  CCLCorePlugin (Code Chicken Lib [3.0.0.274].jar)
  RBLoadingPlugin (Real Bench [1.3.2].jar)
  LoadingPlugin (Sampler [1.71].jar)
  llibrary (LLibrary [1.7.6].jar)
  CoFH Loading Plugin (CoFH Core [4.2.5.11].jar)
  literalascension (Literal Ascension [1.0.2.2].jar)
  CreativePatchingLoader (Creative Core [1.7.4].jar)
  TANLoadingPlugin (Tough As Nails [2.1.0.51].jar)
  ForgelinPlugin (Forgelin [1.4.2].jar)
  LoadingPlugin (Quark [r1.2-93].jar)
  AppleCore (Apple Core [2.2.0].jar)
  LoadingPlugin (Resource Loader [1.5.2].jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (Foam Fix [0.7.0][Anarchy].jar)
  ShetiPhian-ASM (Shetiphian Core [3.4.6].jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 7/1/17 2:55 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tesla Core Lib (teslacorelib)
Caused by: java.lang.NoClassDefFoundError: net/darkhax/tesla/api/implementation/BaseTeslaContainer
	at net.ndrei.teslacorelib.TeslaCoreLib.preInit(TeslaCoreLib.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:647)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:647)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:276)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:440)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 37 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer toughasnails.asm.transformer.CropDecayTransformer@c49e434 from coremod TANLoadingPlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:257)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 39 more
Caused by: java.lang.NullPointerException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at toughasnails.asm.transformer.CropDecayTransformer.transform(CropDecayTransformer.java:46)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:253)
	... 41 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 360132672 bytes (343 MB) / 1659699200 bytes (1582 MB) up to 4187619328 bytes (3993 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.1.2388 Optifine OptiFine_1.11.2_HD_U_C3 157 mods loaded, 157 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2388.jar) 
	UCH	forge{13.20.1.2388} [Minecraft Forge] (forge-1.11.2-13.20.1.2388.jar) 
	UCH	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCH	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCH	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCH	ccl-entityhook{1.0} [ccl-entityhook] (Code Chicken Lib [3.0.0.274].jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCH	accesstweaks{2.1-mc1.11.2} [AccessTweaks] (Access Tweaks [2.1].jar) 
	UCH	akashictome{1.1-7} [Akashic Tome] (Akashic Tome [1.1-7].jar) 
	UCH	atg{2} [Alternate Terrain Generation] (Alternate Terrain Generation [2.1.7].jar) 
	UCH	craftstudioapi{0.3.0-beta} [CraftStudio API] (Craft Studio API [0.3.0.86].jar) 
	UCH	quark{r1.2-93} [Quark] (Quark [r1.2-93].jar) 
	UCH	cofhcore{4.2.5} [CoFH Core] (CoFH Core [4.2.5.11].jar) 
	UCH	animania{1.2} [Animania] (Animania [1.2].jar) 
	UCH	applecore{2.2.0} [AppleCore] (Apple Core [2.2.0].jar) 
	UCH	jei{4.5.0.290} [Just Enough Items] (Just Enough Items [4.5.0.290].jar) 
	UCH	appleskin{1.0.7} [AppleSkin] (Apple Skin [1.0.7].jar) 
	UCH	architect{1.1.3.56} [Architect] (Architect [1.1.3.56].jar) 
	UCH	csb_armorstand{1.0.2} [Armor Stand Configurator] (Armor Stand GUI [1.0.2].jar) 
	UCH	astralsorcery{1.4.4} [Astral Sorcery] (Astral Sorcery [1.4.4].jar) 
	UCH	psi{r1.1-47} [Psi] (Psi [r1.1-47].jar) 
	UCH	autoreglib{1.1-4} [AutoRegLib] (Auto Reg Lib [1.1-4].jar) 
	UCH	avaritia{1.0} [Avaritia] (Avaritia [3.0.2].jar) 
	UCH	barkifier{1.4.1} [Barkifier] (Barkifier [1.4.1].jar) 
	UCH	base{2.0.0} [B.A.S.E] (Base [2.0.0].jar) 
	UCH	basemetals{2.5.0-beta1} [Base Metals] (Base Metals [2.5.0-beta1.45].jar) 
	UCH	baseminerals{2.5.0-beta1} [Base Minerals] (Base Minerals [2.5.0-beta1.14].jar) 
	UCH	baubles{1.4.5} [Baubles] (Baubles [1.4.5].jar) 
	UCH	bedbugs{@VERSION@} [Bed Bugs] (Bed Bugs [1.1.7].jar) 
	UCH	betterquesting{2.4.235} [Better Questing] (Better Questing [2.4.235].jar) 
	UCH	bibliocraft{2.3.2} [BiblioCraft] (Biblio Craft [2.3.2].jar) 
	UCH	biomesoplenty{6.2.0.2267} [Biomes O' Plenty] (Biomes O Plenty [6.2.0.2267].jar) 
	UCH	bibliowoodsbop{2.0} [BiblioWoodBoP] (Biblio Woods [BoP][2.0].jar) 
	UCH	guideapi{1.11.2-2.1.1-52} [Guide-API] (Guide API [2.1.1-52].jar) 
	UCH	bloodmagic{1.11-2.1.11-80} [Blood Magic: Alchemical Wizardry] (Blood Magic [2.1.11-80].jar) 
	UCH	botania{r1.9-344} [Botania] (Botania [r1.9-344].jar) 
	UCH	buildcraftlib{7.99.4} [BuildCraft Lib] (Buildcraft [7.99.4].jar) 
	UCH	buildcraftcore{7.99.4} [BuildCraft] (Buildcraft [7.99.4].jar) 
	UCH	buildcraftfactory{7.99.4} [BC Factory] (Buildcraft [7.99.4].jar) 
	UCH	buildcrafttransport{7.99.4} [BC Transport] (Buildcraft [7.99.4].jar) 
	UCH	buildcraftbuilders{7.99.4} [BC Builders] (Buildcraft [7.99.4].jar) 
	UCH	buildcraftenergy{7.99.4} [BC Energy] (Buildcraft [7.99.4].jar) 
	UCH	buildcraftrobotics{7.99.4} [BC Robotics] (Buildcraft [7.99.4].jar) 
	UCH	buildcraftsilicon{7.99.4} [BC Silicon] (Buildcraft [7.99.4].jar) 
	UCH	chisel{MC1.11.2-0.0.11.18} [Chisel] (Chisel [0.0.11.18].jar) 
	UCH	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle [1.2.0.26].jar) 
	UCH	tconstruct{1.11.2-2.7.0.26} [Tinkers' Construct] (Tinker Construct [2.7.0.26].jar) 
	UCH	ceramics{1.11.2-1.2.2b} [Ceramics] (Ceramics [1.2.2b].jar) 
	UCH	chameleon{1.11.2-3.1.0} [Chameleon] (Chameleon [3.1.0].jar) 
	UCH	chiselsandbits{13.11} [Chisels & Bits] (Chisels And Bits [13.11].jar) 
	UCH	clayworldgen{1.1.0-1.11} [Clay WorldGen] (Clay World Gen [1.1.0].jar) 
	UCH	clumps{2.0.0} [Clumps] (Clumps [2.0.0].jar) 
	UCH	codechickenlib{3.0.0.274} [CodeChicken Lib] (Code Chicken Lib [3.0.0.274].jar) 
	UCH	ctm{MC1.11.2-0.1.1.6} [CTM] (Connected Textures [0.1.1.6].jar) 
	UCH	controlling{2.0.5} [Controlling] (Controlling [2.0.5].jar) 
	UCH	cookingforblockheads{5.3.21} [Cooking for Blockheads] (Cooking For Blockheads [5.3.21].jar) 
	UCH	crafttweakerjei{1.0.2} [CraftTweaker JEI Support] (Craft Tweaker [3.0.26].jar) 
	UCH	crafttweaker{3.0.26} [Crafttweaker] (Craft Tweaker [3.0.26].jar) 
	UCH	ctgui{1.0.0} [CT-GUI] (Craft Tweaker [3.0.26].jar) 
	UCH	creativecore{1.7.4} [CreativeCore] (Creative Core [1.7.4].jar) 
	UCH	custombackgrounds{1.0} [Custom Backgrounds] (Custom Backgrounds [1.1].jar) 
	UCH	custommainmenu{2.0.5} [Custom Main Menu] (Custom Main Menu [2.0.5].jar) 
	UCH	cyberware{alpha-0.2.9} [Cyberware] (Cyberware [0.2.9].jar) 
	UCH	earthworks{1.3.4} [Earthworks] (Earthworks [1.3.4].jar) 
	UCH	elementaria{3.0.2} [Elementaria] (Elementaria [3.0.2].jar) 
	UCH	elevatorid{1.3.2} [Elevator Mod] (Elevator [1.3.2].jar) 
	UCH	embers{0.219} [Embers] (Embers [0.219].jar) 
	UCH	theoneprobe{1.4.7} [The One Probe] (The One Probe [1.4.7].jar) 
	UCH	endercrop{1.11-1.3.4} [Ender Crop] (Ender Crop [1.3.4].jar) 
	UCH	enderstorage{1.0} [EnderStorage] (Ender Storage [2.3.1.116].jar) 
	UCH	entity_hoppers{0.2.0-1.11.2} [Entity Hoppers] (Entity Hoppers [0.2.0].jar) 
	UCH	valkyrielib{1.11.2-0.11.0b} [Valkyrie Lib] (Valkyrie Lib [0.11.0c].jar) 
	UCH	environmentaltech{1.11.2-0.11.0d} [Environmental Tech] (Environmental Tech [0.11.0d].jar) 
	UCH	erosion{2.1.2} [Erosion] (Erosion [2.1.2].jar) 
	UCH	etlunar{1.11.2-0.11.0c} [ET Lunar] (Et Lunar [0.11.0c].jar) 
	UCH	extrabitmanipulation{1.11.2-3.0.6} [Extra Bit Manipulation] (Extra Bit Manipulation [3.0.6].jar) 
	UCH	extratweaker{0.4} [ExtraTweaker] (Extra Tweaker [0.4].jar) 
	UCH	zerocore{1.11.2-0.1.0.6} [Zero CORE] (Zero Core [0.1.0.6].jar) 
	UCH	bigreactors{1.11.2-0.4.5.30} [Extreme Reactors] (Extreme Reactors [0.4.5.30].jar) 
	UCH	fairylights{2.1.0} [Fairy Lights] (Fairy Lights [2.1.0].jar) 
	UCH	fastleafdecay{v12} [Fast Leaf Decay] (Fast Leaf Decay [v12].jar) 
	UCH	foamfix{@VERSION@} [FoamFix] (Foam Fix [0.7.0][Anarchy].jar) 
	UCH	immersiveengineering{0.11-63} [Immersive Engineering] (Immersive Engineering [0.11-63].jar) 
	UCH	undergroundbiomes{1.0.v.18} [Underground Biomes] (Underground Biomes Constructs [1.0.v.19].jar) 
	UCH	primal{0.4.6} [PrimalCore] (Primal Core [0.4.6].jar) 
	UCH	forgecraft{1.2.53} [Kitsu's Forgecraft] (Forge Craft [1.2.53].jar) 
	UCH	forgelin{1.4.2} [Forgelin] (Forgelin [1.4.2].jar) 
	UCH	ftgumod{Minecraft 1.11.2} [From the Ground Up] (From The Ground Up [b1.1.7].jar) 
	UCH	shadowmc{3.7.1} [ShadowMC] (Shadow MC [3.7.5].jar) 
	UCH	funnels{1.2.2} [Funnels] (Funnels [1.2.2].jar) 
	UCH	hopperducts{1.4.9.1} [Hopper Ducts] (Hopper Ducts [1.4.9.1].jar) 
	UCH	horsepower{1.2.0} [Horse Power] (Horse Power [1.2.0.14].jar) 
	UCH	llibrary{1.7.6} [LLibrary] (LLibrary [1.7.6].jar) 
	UCH	iceandfire{1.1.1} [Ice and Fire] (Ice And Fire [1.1.1].jar) 
	UCH	immersivepetroleum{1.0.7} [Immersive Petroleum] (Immersive Petroleum [1.0.7].jar) 
	UCE	teslacorelib{0.7.0} [Tesla Core Lib] (Tesla Core Lib [0.7.0].jar) 
	UCE	industrialforegoing{1.11.2-0.2.2-BETA} [Industrial Foregoing] (Industrial Foregoing [0.3-14].jar) 
	UCH	mtlib{@VERSION@} [MTLib] (MT Lib [2.0.3].jar) 
	UCH	initialinventory{2.0.2} [InitialInventory] (Initial Inventory [2.0.2].jar) 
	UCH	inventorytweaks{1.62+release.90.40cf8fc} [Inventory Tweaks] (Inventory Tweaks [1.62].jar) 
	UCH	ironchest{1.11.2-7.0.25.815} [Iron Chest] (Iron Chest [7.0.25.815].jar) 
	UCH	journeymap{1.11.2-5.4.7} [JourneyMap] (Journey Map [5.4.7].jar) 
	UCH	je_calculation{1.11.2-2.6.4} [Just Enough Calculation] (Just Enough Calculation [2.6.4].jar) 
	UCH	jehc{1.2.2} [Just Enough HarvestCraft] (Just Enough HarvestCraft [1.2.2].jar) 
	UCH	jeresources{0.6.6.12} [Just Enough Resources] (Just Enough Resources [0.6.6.12].jar) 
	UCH	literalascension{1.11.2-1.0.2.2} [Literal Ascension] (Literal Ascension [1.0.2.2].jar) 
	UCH	mcmultipart{2.0.2} [MCMultiPart] (MC MultiPart [2.0.2].jar) 
	UCH	mcanm{2.6.8.138} [Minecraft Animated] (Minecraft Animated [2.6.8.138].jar) 
	UCH	modtweaker{3.0.1} [Mod Tweaker] (Mod Tweaker [3.0.1].jar) 
	UCH	modernmetals{2.5.0-beta1} [Modern Metals] (Modern Metals [2.5.0-beta1.15].jar) 
	UCH	moreplates{1.11.2-10.0} [More Plates] (More Plates [10.0].jar) 
	UCH	morpheus{1.11.2-3.2.14} [Morpheus] (Morpheus [3.2.14].jar) 
	UCH	cfm{4.1.2} [MrCrayfish's Furniture Mod] (Mr Crayfish Furniture [4.1.2].jar) 
	UCH	naturescompass{1.3.0} [Nature's Compass] (Natures Compass [1.3.0].jar) 
	UCH	netherportalfix{1.0} [NetherPortalFix] (Nether Portal Fix [4.3.1].jar) 
	UCH	nofist{5.1.0.1} [No Fist] (No Fist [5.1.0.1].jar) 
	UCH	notes{1.0.1} [Notes] (Notes [1.0.1].jar) 
	UCH	orespawn{3.0.0} [OreSpawn] (Ore Spawn [3.0.0.36].jar) 
	UCH	p455w0rdslib{1.0.15} [p455w0rd's Library] (P455w0rds Lib [1.0.15].jar) 
	UCH	harvestcraft{1.11.2g} [Pam's HarvestCraft] (Pam's HarvestCraft [1.11.2h].jar) 
	UCH	placeableitems{3.0.4.1} [Placeable Items Mod] (Placeable Items [3.0.4.1].jar) 
	UCH	shetiphiancore{3.4.5} [ShetiPhian-Core] (Shetiphian Core [3.4.6].jar) 
	UCH	platforms{1.3.4} [Platforms] (Platforms [1.3.4].jar) 
	UCH	thermalfoundation{2.2.3} [Thermal Foundation] (Thermal Foundation [2.2.4.8].jar) 
	UCH	plustic{5.1.1.0} [PlusTiC] (Plus TiC [5.1.1.0].jar) 
	UCH	reauth{3.5.0} [ReAuth] (Re Auth [3.5.0].jar) 
	UCH	thermalexpansion{5.2.5} [Thermal Expansion] (Thermal Expansion [5.2.5.11].jar) 
	UCH	redstonearsenal{2.2.4} [Redstone Arsenal] (Redstone Arsenal [2.2.4.6].jar) 
	UCH	sandro.redstone{1.1c} [Redstone++] (Redstone++ [1.1c].jar) 
	UCH	sandro{1.1a} [Sandro's Core] (Redstone++ [1.1c].jar) 
	UCH	refinedstorage{1.4.18} [Refined Storage] (Refined Storage [1.4.18].jar) 
	UCH	xreliquary{1.11.2-1.3.3.653} [Reliquary] (Reliquary [1.3.3.653].jar) 
	UCH	resourceloader{1.5.2} [Resource Loader] (Resource Loader [1.5.2].jar) 
	UCH	rftools{6.10} [RFTools] (RF Tools [6.10].jar) 
	UCH	rftoolscontrol{1.6.8} [RFTools Control] (RF Tool Control [1.6.8].jar) 
	UCH	roots{0.024} [Roots 2] (Roots 2 [0.024].jar) 
	UCH	ropebridge{2.0.5} [Rope Bridge] (Rope Bridge [2.0.6].jar) 
	UCH	sampler{1.71} [Sampling Performance Profiler] (Sampler [1.71].jar) 
	UCH	scannable{1.4.0.23} [Scannable] (Scannable [1.4.0.23].jar) 
	UCH	signpost{1.05.5} [Sign Post] (SignPost [1.05.5].jar) 
	UCH	simplytea{1.1} [Simply Tea] (Simply Tea [1.1].jar) 
	UCH	spartanshields{1.3} [Spartan Shields] (Spartan Shields [1.3a].jar) 
	UCH	spiceoflife{1.3.8} [The Spice of Life] (Spice Of Life [1.3.8].jar) 
	UCH	bq_standard{2.4.132} [Standard Expansion] (Standard Expansion [2.4.132].jar) 
	UCH	thermaldynamics{2.2.5} [Thermal Dynamics] (Thermal Dynamics [2.2.5.8].jar) 
	UCH	tombmanygraves{1.11.2-3.0.9} [Tomb Many Graves] (Tomb Many Graves [3.0.9].jar) 
	UCH	toolbelt{1.6.1} [Tool Belt] (Tool Belt [1.6.1].jar) 
	UCH	torchmaster{1.4.0.45} [TorchMaster] (Torch Master [1.4.0.45].jar) 
	UCH	totemic{1.11.2-0.8.7} [Totemic] (Totemic [0.8.7].jar) 
	UCH	toughasnails{2.1.0.51} [Tough As Nails] (Tough As Nails [2.1.0.51].jar) 
	UCH	tanspit{@VERSION@} [Campfire Spit] (Tough As Nails Spit [1.3].jar) 
	UCH	tanaddons{3.0.9} [Tough Expansion] (Tough Expansion [3.0.9].jar) 
	UCH	treechopper{1.1.2} [Tree Chopper] (Tree Chopper [1.1.2].jar) 
	UCH	wearablebackpacks{2.5.0} [Wearable Backpacks] (Wearable Backpacks [2.5.0].jar) 
	UCH	wolfarmor{1.3.2} [Wolf Armor and Storage] (Wolf Armor [1.3.3.6].jar) 
	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (Inventory Tweaks [1.62].jar)
  invtweaks.forge.asm.ContainerTransformer
AstralCore (Astral Sorcery [1.4.4].jar)
  
CTMCorePlugin (Connected Textures [0.1.1.6].jar)
  team.chisel.ctm.client.asm.CTMTransformer
CCLCorePlugin (Code Chicken Lib [3.0.0.274].jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
RBLoadingPlugin (Real Bench [1.3.2].jar)
  pw.prok.realbench.asm.RBTransformer
LoadingPlugin (Sampler [1.71].jar)
  
llibrary (LLibrary [1.7.6].jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CoFH Loading Plugin (CoFH Core [4.2.5.11].jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
literalascension (Literal Ascension [1.0.2.2].jar)
  com.jamieswhiteshirt.literalascension.core.patcher.LiteralAscensionRuntimePatcher
CreativePatchingLoader (Creative Core [1.7.4].jar)
  
TANLoadingPlugin (Tough As Nails [2.1.0.51].jar)
  toughasnails.asm.transformer.CropDecayTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
ForgelinPlugin (Forgelin [1.4.2].jar)
  
LoadingPlugin (Quark [r1.2-93].jar)
  vazkii.quark.base.asm.ClassTransformer
AppleCore (Apple Core [2.2.0].jar)
  squeek.applecore.asm.TransformerModuleHandler
LoadingPlugin (Resource Loader [1.5.2].jar)
  lumien.resourceloader.asm.ClassTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (Foam Fix [0.7.0][Anarchy].jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
ShetiPhian-ASM (Shetiphian Core [3.4.6].jar)
  shetiphian.core.asm.ClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4550' Renderer: 'Intel(R) HD Graphics 620'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	codechickenlib Invalid Fingerprint Reports: - No invalid fingerprints.: 
	enderstorage Invalid Fingerprint Reports: - No invalid fingerprints.: 
	OptiFine Version: OptiFine_1.11.2_HD_U_C3
	Render Distance Chunks: 4
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 21.20.16.4550
	OpenGlRenderer: Intel(R) HD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by faceofcat** [comment]
do you have Tesla mod installed?... it is listed as a required mod on curse forge.

**Comment by LuxerTheGamer** [comment]
Yes.
UCE	teslacorelib{0.7.0} [Tesla Core Lib] (Tesla Core Lib [0.7.0].jar)

**Comment by faceofcat** [comment]
no.... this: https://minecraft.curseforge.com/projects/tesla

**Comment by LuxerTheGamer** [comment]
Thanks. Now working :)
