### ISSUE TITLE
Crash Logs please support

### ISSUE THREAD

**Issue by Siervena** [faceofcat/Tesla-Core-Lib#42]
https://hastebin.com/natakoceci.md

http://prntscr.com/jrqumg

http://prntscr.com/jrqw71

http://prntscr.com/jrqx6o

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tesla Core Lib (teslacorelib)

**Comment by faceofcat** [comment]
are you missing the Tesla library?

**Comment by Siervena** [comment]
Not sure, tell me where to find the lib

**Comment by faceofcat** [comment]
https://minecraft.curseforge.com/projects/tesla

**Comment by faceofcat** [comment]
I'm guessing he was missing the lib.
