### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Shybella** [faceofcat/Tesla-Core-Lib#43]
Spark profile: http://prntscr.com/jv2kj0

sync tile entity seems to be hitting hard on tickloop. If you need any more information I'll do my best to help.

Thank you.

**Comment by faceofcat** [comment]
well... I can't see that screenshot... :(... or whatever that is..

**Comment by Shybella** [comment]
It's a very popular screenshot sharing application.

![rd8t1xcgrrkh7jg_ufxt9w](https://user-images.githubusercontent.com/4436776/41475499-87ec5cd6-7099-11e8-9331-f8851be08c86.png)

**Comment by faceofcat** [comment]
what version of TCL is this?... also do you have any idea what tile entity is doing this?

**Comment by Sir-Will** [comment]
Same issue here, the only mod I have which uses teslacorelib is industrial foregoing.

Also here are the top packs which get send:
```
                  Packet | Count |    Size
            teslacorelib | 10252 |   1.5MB
               applecore |  7212 |  91.6KB
 SPacketUpdateTileEntity |  5806 |   1.4MB
 SPacketEntityProperties |  3836 | 145.7KB
     SPacketUpdateHealth |  3606 |  35.2KB
                  Packet | Count |    Size
        SPacketChunkData |   226 |   8.4MB
            teslacorelib | 10252 |   1.5MB
 SPacketUpdateTileEntity |  5806 |   1.4MB
    rc&reborncore.&39932 |   320 |   1.1MB
       actuallyadditions |  3460 | 690.6KB
```

**Comment by faceofcat** [comment]
can you say what tile entities are you using from IF?... or are you using many of them?

**Comment by Sir-Will** [comment]
It's on a server with a lot of players, so pretty much all of them.

**Comment by Sir-Will** [comment]
I wonder why it needs to sync the machines on every update and not only when the player opens it.

**Comment by faceofcat** [comment]
same here... as far as I remember the latest TCL (also a series of prior versions) should have this fixed and updates should only happen if a GUI is opened... unless otherwise specified.

I promise to make time soon to look at this :)

**Comment by faceofcat** [comment]
changed the defaults... should be a lot better now...

can one of you please test against the maven version: https://maven.mcmoddev.com/net/ndrei/tesla-core-lib/1.12.2-1.0.15.12/
