### ISSUE TITLE
tesla-core-lib-1.12.2-1.0.15 crashes the game

### ISSUE THREAD

**Issue by VodkaJo** [faceofcat/Tesla-Core-Lib#46]
https://pastebin.com/P6SVb8mi

everything goes good till i add tesla-core-lib-1.12.2-1.0.15

the game crashes :-1: 
and im not missing any required files :)

thanks in advanced

**Comment by faceofcat** [comment]
for some reasons it crashes with:

```
> [05:06:00] [main/ERROR] [FML]: An exception was thrown, the game will display an error screen and halt.
> net.minecraftforge.fml.common.MissingModsException: Mod industrialforegoing (Industrial Foregoing) requires [teslacorelib@[1.0.15,)]
```
:|

I don't see any other errors related with my lib...

**Comment by VodkaJo** [comment]
just don't get it 🤨
when I delete the lib, the game asks for it as required
when I add it back, the game crashes 😂

how to fix?? 🤔

**Comment by jriwanek** [comment]
Using cracked launcher, and by the looks of the log, hasn't actually paid for minecraft either, support will NOT be provided. We do not support piracy or help pirates around here, go pay for the game, download and use a non cracked launcher and then come back and ask for help.
