### ISSUE TITLE
Add tesla and forgelin as required on startup.

### ISSUE THREAD

**Issue by UnPure** [faceofcat/Tesla-Core-Lib#5]
Hey there.
I'm currently trying to create a small modpack.
To use [Industrial Foregoing](https://minecraft.curseforge.com/projects/industrial-foregoing?gameCategorySlug=mc-mods&projectID=266515) i need to use TeslaCoreLib.
When using TeslaCoreLib the game is just crashing. 
This seems related to [this issue](https://github.com/faceofcat/Tesla-Core-Lib/issues/4) because adding the Tesla mod and Forgelin fixes that problem.
I know that these mods are stated as required on curseforge.
My question/request ist that you add that requirement to the startup.
Other mods tell you if a mod is missing instead of just crashing.
I'm sure many other people will have that problem too so this would prevent many issues on this github page.

**Comment by faceofcat** [comment]
that's actually a good idea... :)... will try to add that!

**Comment by faceofcat** [comment]
1.12 - 1.0.4 should have that...
