### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by AnnaTheKitty** [faceofcat/Tesla-Core-Lib#54]
I believe the reason why that my server crashed was from this mod.

[06:16:11] [Server thread/WARN] [teslacorelib]: Annotated class 'net.ndrei.teslacorelib.blocks.multipart.MultiPartBlockEvents' not found!
[06:16:13] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception

You can look the rest of logs at https://pastebin.com/DtbPXbmv

Update:
I reinstalled all of my mods, made sure all of the mods are up to date, updated forge to the latest version (1.12.2), and even the recommended version, still getting the same error.

Updated logs: https://pastebin.com/ks5LsEbD
Crash Report: https://pastebin.com/2ZN4gtc5

**Comment by AnnaTheKitty** [comment]
I reinstalled all of my mods, made sure all of the mods are up to date, updated forge to the latest version (1.12.2), and even the recommended version, still getting the same error.

Updated logs: https://pastebin.com/ks5LsEbD
Crash Report: https://pastebin.com/2ZN4gtc5

**Comment by faceofcat** [comment]
well...

```
[08:26:38] [Server thread/WARN] [teslacorelib]: Annotated class 'net.ndrei.teslacorelib.blocks.multipart.MultiPartBlockEvents' not found!
[08:26:39] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
        at mod.mcreator.mcreator_lavaTNT.<clinit>(mcreator_lavaTNT.java:80) ~[mcreator_lavaTNT.class:?]
```

my mod throws an warning... :)

mcreator throws an error... how is that my fault?

**Comment by AnnaTheKitty** [comment]
> well...
> 
> ```
> [08:26:38] [Server thread/WARN] [teslacorelib]: Annotated class 'net.ndrei.teslacorelib.blocks.multipart.MultiPartBlockEvents' not found!
> [08:26:39] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
> java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
>         at mod.mcreator.mcreator_lavaTNT.<clinit>(mcreator_lavaTNT.java:80) ~[mcreator_lavaTNT.class:?]
> ```
> 
> my mod throws an warning... :)
> 
> mcreator throws an error... how is that my fault?

My mistake, sorry, at first it looked like the warn caused the error, seems I didn't read through it more. Thanks for telling what was the problem of my server at least lol
