### ISSUE TITLE
Registry Issue 

### ISSUE THREAD

**Issue by SarisVanguard** [faceofcat/Tesla-Core-Lib#57]
I have downloaded Tesla already. I keep getting this error no matter what version I try:

25.03 17:27:38 [Server] Server thread/ERROR [FML]: Unidentified mapping from registry minecraft:items
25.03 17:27:38 [Server] Server thread/ERROR [FML]:     teslacorelib:gear_stone: 6413
25.03 17:27:38 [Server] Server thread/ERROR [FML]:     teslacorelib:gear_diamond: 6412
25.03 17:27:38 [Server] Server thread/ERROR [FML]:     teslacorelib:gear_iron: 6495
25.03 17:27:38 [Server] Server thread/ERROR [FML]:     teslacorelib:gear_gold: 6558
25.03 17:27:38 [Server] Server thread/WARN [FML]: Forge Mod Loader detected missing registry entries.
25.03 17:27:38 [Server] INFO If you continue the missing entries will get removed.
25.03 17:27:38 [Server] INFO A world backup will be automatically created in your saves directory.
25.03 17:27:38 [Server] INFO Missing minecraft:items:
25.03 17:27:38 [Server] INFO teslacorelib:gear_diamond
25.03 17:27:38 [Server] INFO teslacorelib:gear_iron
25.03 17:27:38 [Server] INFO teslacorelib:gear_gold
25.03 17:27:38 [Server] INFO teslacorelib:gear_stone

**Comment by faceofcat** [comment]
there should be a config for them... maybe that changed?

were you upgrading from a previous version of TCL?

**Comment by SarisVanguard** [comment]
This is a new server and I wasn't trying to upgrade from a previous version. I did try to edit the config files to either # out the code or delete it all together. The solution I found was to literally move thermal foundations (after I realized that was the conflicting mod) above this one in the load order by manually renaming it.
