### ISSUE TITLE
Only wrench shows in JEI

### ISSUE THREAD

**Issue by viveleroi** [faceofcat/Tesla-Core-Lib#58]
I'd prefer to ask this before reporting it as an issue in discord but the invite link is invalid.

I have Industrial Foregoing which needs TeslaCoreLib. They advised that their machines take speed/energy upgrades which are items from TeslaCoreLib, yet JEI shows only one item for me: the wrench.

I'm using `tesla-core-lib-1.12.2-1.0.17.jar`. Is there anything I could be missing or misunderstanding?

1.12.2 (modded) forge-14.23.5.2847

**Comment by Guilherme-SMoraes** [comment]
I'm having the same issue, any solution yet?

**Comment by Guilherme-SMoraes** [comment]
Okay, it's a configuration problem, just change some configurations of the mod and the upgrades will appear

**Comment by faceofcat** [comment]
yeah... TLC items (except the wrench) should only appear if they are "turned on" by any mod... if they are not used they are not even registered I think...
