### ISSUE TITLE
Can't seem to fix this on a custom pack me and a few friends are making.  [Server thread/WARN] [teslacorelib]: Annotated class 'net.ndrei.teslacorelib.blocks.multipart.MultiPartBlockEvents' not found!

### ISSUE THREAD

**Issue by FBIPenguin** [faceofcat/Tesla-Core-Lib#59]
We had installed Industrial Foregoing, and so tesla-core-lib came along with it.   We installed a mod named forgelin' (I think that was the name), but that hadn't worked.  I'll attach a link to the log below, but we haven't been able to figure it out.  I'm not really sure what else to do, so if there's something I can do to help someone figure it out, it shouldn't be an issue.

Log:
https://mclo.gs/uY1bXwu

I should mention that we will likely be taking out the tesla-powered-thingies mod because that was one of our attempts to fix the issue, and it didn't help either.

**Comment by faceofcat** [comment]
the only error I see in the logs is: 
" The mod 'Industrial Foregoing' is missing the required mod 'teslacorelib'. "

seems you are missing Tesla Core Lib... :|

**Comment by FBIPenguin** [comment]
We added Tesla Core Lib, but that hadn't worked either.  I'll send an earlier log that had it, but you should know that we've tried a bunch of things like adding the TESLA mod along with the Tesla Core Lib and still nothing.

Log:
https://mclo.gs/rtDnnRm
(It's the same thing as the past log, where we'll likely be removing the tesla powered thingies mod as it didn't really help).

**Comment by faceofcat** [comment]
why do you have `./mods/TESLA-1.12.2.jar` ?... what mod is that?

**Comment by FBIPenguin** [comment]
It was a suggested mod that may have come with the TeslaCoreLib, but it didn't work either so we might be taking it out as well.

**Comment by FBIPenguin** [comment]
It was on a forum that we tried looking at, and here's the curse link to the mod.  

Link:
https://www.curseforge.com/minecraft/mc-mods/tesla

**Comment by faceofcat** [comment]
just remove it... you probably have the wrong file... :|

**Comment by FBIPenguin** [comment]
We will be doing that, but even then.  It gives us this error message:

[teslacorelib]: Annotated class 'net.ndrei.teslacorelib.blocks.multipart.MultiPartBlockEvents' not found!

**Comment by faceofcat** [comment]
yeah... please provide me with a log with just that error... :)

**Comment by FBIPenguin** [comment]
That may take a bit since I'm not actually the one running the server, I'm just looking into the issue.  There will likely be someone else who gives you a log soon, so I'm sorry about that delay.

**Comment by justinquinnb** [comment]
> yeah... please provide me with a log with just that error... :)

Hey, I'm the guy running the server. Sorry for the long delay, I didn't know my friend wanted me to send the log until just now. The link is here: https://mclo.gs/PcTqoWC

We tried booting up the server with teslacorelib installed and it consistently throws us the error seen at line 829. We've tried reinstalling the mods that seem to be related to no avail. The server is running the latest version of Forge for 1.12.2 (version 14.23.5.2854). I can send additional logs if needed, just let me know. I can also send a link to the full modpack if necessary. Thanks for getting back to us by the way, we've been trying to figure this out for a few days now!

**Comment by faceofcat** [comment]
according to that log your problem is not in Tesla Core Lib... that's just a warning that the lib spits out... you can ignore it... :)

**Comment by justinquinnb** [comment]
Hmm... but as soon as that warning is given, the errors seem to appear and the server fails to start.  If it isn't teslacorelib, any idea what the problem could be based on the log?

**Comment by faceofcat** [comment]
well... you could try what that log analyser is suggesting you :)

![image](https://user-images.githubusercontent.com/23014228/85323851-773ef280-b4d1-11ea-9951-2686b3606f44.png)

Applied Energistics should have nothing to do with Tesla Core Lib...

**Comment by justinquinnb** [comment]
Oh, duh. Will do! Tysm for your help!

**Comment by FBIPenguin** [comment]
That seems to have led us in the right direction, so thank you for your help!
