### ISSUE TITLE
Crash with mod interaction between Mekanism and Tesla Core Lib

### ISSUE THREAD

**Issue by GuntherDW** [faceofcat/Tesla-Core-Lib#7]
When I upgraded from 1.0.5 to 1.0.6 (as a dependancy for Industrial Foregoing) I noticed my world crashed.
I've then narrowed it down to the Mekanism power cables connecting to said mod's blocks (Industrial Foregoing).
It looks like either the Mek integration isn't entirely implemented, or Mek calling the wrong methods, but it looks more likely to be the first?

Link to the crash report :
https://pastebin.com/4FVvJBUf

Versions:
 - Minecraft : 1.12
 - Tesla-Core-Lib : 1.12-1.0.6
 - Industrial Foregoing : 1.1-24
 - Mekanism : https://github.com/aidancbrady/Mekanism/commit/8ed83b0e4ff241aaa7e17c09e85c932d29f2dc76

**Comment by faceofcat** [comment]
should be fixed in 1.0.7
